package com.sachira.spring_backend.utils;

import com.sachira.spring_backend.entity.User;
import com.sachira.spring_backend.repo.UserRepo;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import io.jsonwebtoken.io.Decoders;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.security.Key;
import java.util.Date;
import java.util.Optional;

@Component
public class JWTAuthenticator {
    @Autowired
    UserRepo userRepo;

    private final String jwtSecret="TT39qaRA06FZyUGCVw0wD8SFnRvPR51M+JmZkLJDP4A=";
    private final int jwtExpirationMs=86400000;

    //generate JWT Token
    public String generateJwtToken(User user) {
        return Jwts.builder()
                .subject((user.getEmail()))
                .id(Integer.toString(user.getId()))
                .issuedAt(new Date())
                .expiration(new Date((new Date()).getTime() + jwtExpirationMs))
                .signWith(key(), SignatureAlgorithm.HS256)
                .compact();
    }

    public User getUserByToken(String token){
        String jwtToken = token.substring("Bearer ".length());
        String id = Jwts.parser().setSigningKey(key()).build().parseClaimsJws(jwtToken).getBody().getId();

       Optional<User> user= userRepo.getUserById(Integer.parseInt(id));
       System.out.println(user.get().getId());
       return user.get();
    }

    private Key key() {
        return Keys.hmacShaKeyFor(Decoders.BASE64.decode(jwtSecret));
    }

    //Validate token ---> verify the token is generated by us
    public boolean validateJwtToken(String authToken) {
        String jwtToken = authToken.substring("Bearer ".length());
        try {
            Jwts.parser().setSigningKey(key()).build().parse(jwtToken);
            return true;
        } catch (Exception e) {
            System.out.println("Error occurred when validate....");
        }
        return false;
    }
}
